# -*- coding: utf-8 -*-
"""task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ejPq0Ic8Jw9zVMi42ooY9YZjg5aFjcAz
"""

print("my name is osama nosehy ")